Added universal error handling for routes
souprogram/sou-program pull request #2
Opened 2024-01-11 00:47 UTC by alanbubalo

2024-01-12 07:32 UTC, souprogram requested changes

2024-01-12 07:32 UTC, souprogram commented on backend/src/middlewares/errorMiddleware.js
> +    res.status(500).send('Something went wrong.');
Pokusaj implementirati da u developmentu prikaze pravi error i pravi status kod, a na produkciji 500 i "something went wrong"

2024-01-12 07:33 UTC, souprogram commented
@alanbubalo Probaj jos vidjet ako se moze kako izbjeci da na svaku rutu moras stavljat tryCatch(async...). Mozda nekako kroz middleware

2024-01-12 20:02 UTC, alanbubalo commented
Middleware kao ostali npr authMiddleware nece moci. Middleware je samo funkcija koja se poziva prije/nakon route funkcije i ne moze znati sto ce se kasnije desiti. Može se npr tryCatch wrappat u router fileovima pa da ne bude u kontroleru.

2024-02-14 19:00 UTC, souprogram approved these changes

2024-02-14 19:11 UTC, merged